- name: bootstrap
  hosts: control
  vars:
    mas_installed_apps:
      - { id: 443987910, name: "1Password (6.8.9)" }
      - { id: 747648890, name: "Telegram (4.3.4)" }
      - { id: 946399090, name: "Telegram Desktop" }
      - { id: 904280696, name: "Things 3 (3.6.2)" }
      - { id: 803453959, name: "Slack (3.3.2)" }
      - { id: 880001334, name: "Reeder (3.2)" }
      - { id: 409789998, name: "Twitter (4.3.2)" }
      - { id: 1091189122, name: "Bear (1.6.1)" }
      - { id: 1265763895, name: "VK Messenger (3.10.1)" }
      - { id: 425424353, name: "The Unarchiver (4.0.0)" }
  roles:
    - geerlingguy.mas
  tasks:
    - name: Ensure custom Terminal profile is added
      shell: open ~/tmp/profile.terminal
      # changed_when: false
      # when: "'JJG-Term' not in terminal_theme.stdout"
    - name: install dev apps
      homebrew:
        name:
          # - python3 # python 3.5.6_1 is needed for ansible
          - go
          - postgresql
          - mysql
          - redis
          - mongodb
          - nginx
    - name: install cli apps
      homebrew:
        name:
          - wget
          - htop
          - aria2
          - imagemagick
          - rclone
          - youtube-dl
          - hugo
          - gettext # from gnu tool for django mesages
        state: present
    - name: install GUI apps
      homebrew_cask:
        name:
          - calibre
          - google-chrome
          - freeze
          - iina
          - jiggler
          - skype
          - sublime-text
          - tunnelblick
          - transmission
          - vmware-fusion
          - whatsapp
          - vlc
          # - chromium
          # - macvim
          # - github
          # - firefox
          # - teamviewer
          # - nightowl
          # - tower
          # - boxer
          # - launchrocket
          # - cyberduck
        state: present
    - name: install jetbrains IDEs
      homebrew_cask:
        name:
          - pycharm
          - goland
    - name: install fuse
      homebrew_cask:
        name: osxfuse
    #     - homebrew:
    #         name:
    #           - sshfs
    #           - ext4fuse
    - name: install pentest tools
      block:
        - homebrew_cask: 
            name:
              - burp-suite
