mas_installed_apps:
  - { id: 747648890, name: "Telegram (4.3.4)" }	
  - { id: 904280696, name: "Things 3 (3.6.2)" }
  - { id: 1091189122, name: "Bear (1.6.1)" }
  - { id: 425424353, name: "The Unarchiver (4.0.0)" }
  - { id: 409201541, name: "Pages (8.0)" }
  - { id: 409203825, name: "Numbers (6.1)" }
  - { id: 497799835, name: "Xcode" }
  - { id: 1039633667, name: "Irvue" }

homebrew_installed_packages:
  - htop
  - imagemagick
  - postgresql
  - redis
  - wget

  # dev stuff
  - pyenv
  - pyenv-virtualenv
  - jupyterlab

  # - mariadb
  # - mongodb
  # - nodejs
  # - nginx
  # - rclone
  # - youtube-dl
  # - hugo
  # - gettext # from gnu tool for django mesages

homebrew_cask_apps:
  - chromium
  - cryptomator
  - freeze
  - iina
  - iterm2
  - jiggler
  - skype
  - soulver
  - tableplus
  - textmate
  - tower
  - transmission
  - tunnelblick
  - vlc
  - vmware-fusion
  - whatsapp

  # dev
  - pycharm
  # - webstorm
  # - goland
  # - docker

  - calibre
  - sublime-text
  # - burp-suite
  # - cyberduck
  # - google-chrome
  # - macvim
  # - osxfuse
  # - virtualbox
  # - virtualbox-extension-pack 

composer_packages: []
gem_packages: []
pip_packages: []
npm_packages: []
  # - name: peerflix
  #   state: present # present/absent/latest, default: present
