mas_installed_apps:
  - { id: 443987910, name: "1Password (6.8.9)" }
  - { id: 747648890, name: "Telegram (4.3.4)" }
  - { id: 946399090, name: "Telegram Desktop" }
  - { id: 904280696, name: "Things 3 (3.6.2)" }
  - { id: 803453959, name: "Slack (3.3.2)" }
  - { id: 880001334, name: "Reeder (3.2)" }
  - { id: 409789998, name: "Twitter (4.3.2)" }
  - { id: 1091189122, name: "Bear (1.6.1)" }
  - { id: 1265763895, name: "VK Messenger (3.10.1)" }
  - { id: 425424353, name: "The Unarchiver (4.0.0)" }
  - { id: 425424353, name: "The Unarchiver (4.0.0)" }
  - { id: 1039633667, name: "Irvue (2.7)" }
  - { id: 409201541, name: "Pages (8.0)" }

homebrew_installed_packages:
  - wget
  - htop
  - rclone
  - youtube-dl
  - gettext # from gnu tool for django mesages
  - postgresql
  - go
  - mariadb
  - mongodb
  - nodejs
  # - hugo
  # - aria2
  # - imagemagick
  # - redis
  # - nginx

homebrew_cask_apps:
  - calibre
  - google-chrome
  - freeze
  - iina
  - jiggler
  - skype
  - sublime-text
  - tunnelblick
  - transmission
  - vmware-fusion
  - whatsapp
  - pycharm
  - goland
  - osxfuse
  - send-to-kindle
  - cyberduck
  # - vlc
  # - burp-suite

composer_packages: []
gem_packages: []
pip_packages: []
npm_packages: []
  # - name: peerflix
  #   state: present # present/absent/latest, default: present
