- name: bootstrap
  hosts: control
  roles:
    - role: geerlingguy.homebrew
      tags: ['homebrew']
    - role: geerlingguy.mas
      when: mas_installed_apps
      tags: ['mas']
  vars_files:
    - mac.config.yml
  tasks:
    - include_tasks: tasks/terminal.yml
      # when: configure_terminal
    - include_tasks: tasks/extra-packages.yml
      tags: ['extra-packages']