- name: install dev apps
  homebrew:
    name:
      # - python3 # python 3.5.6_1 is needed for ansible
      - go
      - postgresql
      - mysql
      - redis
      - mongodb
      - nginx
- name: install cli apps
  homebrew:
    name:
      - wget
      - htop
      - aria2
      - imagemagick
      - rclone
      - youtube-dl
      - hugo
      - gettext # from gnu tool for django mesages
    state: present